// <auto-generated />
namespace STS.Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201305061047298_init migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
